#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS.
# Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL.
# USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
passwd_file="/etc/passwd"

while IFS=":" read -r user pw uid gid uinfo homedir shell
do
	echo "The user $user is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $pw, more info about the user here: $uinfo"
done < "$passwd_file"
