#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters:
# $1 - The path to the file to be transferred
# $2 - The IP of the server we want to transfer the file to
# $3 - The username scp connects with
# $4 - The path to the SSH private key that scp uses

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/

# Display success message
echo "$file_path transferred successfully to $username@$server_ip:~/"
