#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAProxy on lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Check if haproxy installation was successful
if [ $? -ne 0 ]; then
    echo "Error: HAProxy installation failed."
    exit 1
fi

# Edit config file
server_config=\
"
frontend  cysoft_frontend
        bind *:80
        mode http
        default_backend cysoft_backend
backend cysoft_backend
        balance roundrobin
        server 471746-web-01 52.86.39.45:80 check
        server 471746-web-02 18.209.225.164:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
