#!/usr/bin/env bash
# bash script that displays a list of all currently running process.
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps auxf
