#!/usr/bin/env bash

cleanup()
{
    rm -f /var/run/myscript.pid;
    exit
}
# Trap SIGINT signal
trap "echo 'Y U no love me?!'" SIGINT
# Trap SIGTERM & SIGQUIT signal
trap "echo 'I hate the kill command'; cleanup" SIGTERM
trap "echo 'I hate the kill command'; cleanup" SIGQUIT

# Get script's PID and save to file.
echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
