#!/usr/bin/env bash
# script that creates the file /var/run/myscript.pid containing its PID
# displays To infinity and beyond indefinitely
# displays I hate the kill command when receiving a SIGTERM signal
# displays Y U no love me?! when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

cleanup()
{
    rm -f /var/run/myscript.pid;
    exit
}
# Trap SIGINT signal
trap "echo 'Y U no love me?!'" SIGINT
# Trap SIGTERM & SIGQUIT signal
trap "echo 'I hate the kill command'; cleanup" SIGTERM
trap "echo 'I hate the kill command'; cleanup" SIGQUIT

# Get script's PID and save to file.
echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
