#!/usr/bin/env bash

if [ "$1" == "start" ]
then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
    echo "manage_my_process stopped"
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    rm /tmp/my_process
elif [ "$1" == "restart" ]
then
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    rm /tmp/my_process
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
