#!/usr/bin/env bash
# script that displays lines containing the bash word from preious exercise.
# shellcheck disable=SC2009
# line 3 disables the shellcheck suggestion for using pgrep instead of grep as ps output.

ps auxf | grep "bash"
