#!/usr/bin/env bash
# script that stops (kills) 4-to_infinity_and_beyond process,
# which is another script running in another terminal (need -f to find pid)

kill "$(pgrep -f "4-to_infinity_and_beyond")"
