#!/usr/bin/env bash
# script receives kill signal from another script running in another terminal
# and instead of being terminated, kill signal is caught and ignored;
# printing message instead.

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done
