#!/usr/bin/env bash
#  script that displays: The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
command=$(ls)
for FILE in $command
do
	echo "$FILE" | cut -d "-" -f2
done
