#!/usr/bin/env bash
# script that gives you information about the school file. (using if and else)
# -e flag to check if file exists
# -s to check if it's empty
# -f to check if it's a regular file
file="school"

if [ -e "$file" ]; then
	echo "$file file exists"

  	if [ -s "$file" ]; then
    	echo "$file file is not empty"
  	else
    	echo "$file file is empty"
  	fi

  	if [ -f "$file" ]; then
    	echo "$file is a regular file"
  	fi
else
  	echo "$file file does not exist"
fi
